# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85bd231fd32aa89c0c5982cc7b664014a17941b24a7ba6f471997530b46e248ce4678ac582606e5d7b74dab8fcc3b0c8df2f0941d67a3976980cbdc2a332eb4f

test:
  secret_key_base: 420e0ef64bae220904b24adce64c10149aa33f469c0265decdfe73428056f9eb4050ddb0e6980a31044b2684da4f8a0f94a0b3b4e1df2ecbdec2207d940879db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
